"""Adapter wiring the late-bonding pocket to a REAL Solana wallet (22/08).

Three pieces already existed and did their job in isolation:

  * `services/jupiter.py`          -- executable quotes
  * `onchain/jupiter_swap_signer`  -- simulate, sign, send, await finalized
  * `solana_trade_pilot`           -- gate, kill-switch, caps, journalling

Nothing connected them, so the pocket's `execute_fn` seam stayed empty. This
module is that connection and nothing more: it holds no policy of its own, adds
no cap, and cannot bypass anything. Every real buy still goes THROUGH
`solana_trade_pilot.attempt_buy`, which is where the refusals live.

Balance is read fresh from mainnet on every attempt and converted with a live
SOL/USD price. A price that cannot be read returns None, which the pilot treats
as fail-closed -- an unpriced balance blocks the trade rather than being
assumed. That is deliberate: the alternative is trading against a stale
exchange rate, which silently breaks the dollar cap the operator set.

Ships unusable: the pilot's gate is OFF and no key file exists until the
operator creates one.
"""

from __future__ import annotations

import logging
import os

import httpx

from aria_core import solana_trade_pilot
from aria_core.onchain import jupiter_swap_signer, jupiter_swap_simulation
from aria_core.services import jupiter
from aria_core.services.coingecko import coingecko_client
from aria_core.services.pumpswap_ws import require_solana_rpc_http

logger = logging.getLogger(__name__)

# Where the delegate key lives. No default path baked into the signer itself
# (fail-closed by design there), so the choice is made here, once, and stays
# greppable. chmod 600, generated by solana-keygen, never read into a log.
KEY_PATH_ENV = "ARIA_SOLANA_DELEGATE_KEY_PATH"
DEFAULT_KEY_PATH = "/opt/aria-data/agent-wallet-solana-mainnet/delegate.json"

# Lamports kept untouched for fees and rent-exemption. A Solana token account
# costs ~0.00204 SOL to open and every transaction pays a fee; a wallet drained
# to zero cannot even sell what it holds. Roughly 0.01 SOL of headroom.
RESERVED_LAMPORTS = 10_000_000


def key_path() -> str:
    return (os.environ.get(KEY_PATH_ENV, "") or "").strip() or DEFAULT_KEY_PATH


def delegate_key_available() -> bool:
    """True only if the key file really exists AND is not group/world readable.
    The signer refuses a loose key anyway; checking here lets the caller know
    BEFORE a trade is attempted rather than after."""
    path = key_path()
    try:
        st = os.stat(path)
    except OSError:
        return False
    return not (st.st_mode & 0o077)


async def get_balance_usd(*, client: httpx.AsyncClient | None = None) -> float | None:
    """Spendable balance in dollars, or None if anything is unknown.

    None is a REFUSAL upstream, never a zero: the pilot blocks when the balance
    cannot be read. Reserved lamports are subtracted here so the cap applies to
    what is genuinely spendable, not to a total that includes money the wallet
    must keep to pay its own fees.
    """
    owns = client is None
    client = client or httpx.AsyncClient(timeout=20.0)
    try:
        try:
            from solders.keypair import Keypair
            import json

            with open(key_path(), encoding="utf-8") as fh:
                pubkey = str(Keypair.from_bytes(bytes(json.load(fh))).pubkey())
        except Exception as exc:  # noqa: BLE001 -- no key, no balance, no trade
            logger.info("solana_agent_wallet: cannot resolve wallet pubkey (%s)", exc)
            return None

        try:
            resp = await client.post(
                require_solana_rpc_http(),
                json={"jsonrpc": "2.0", "id": 1, "method": "getBalance", "params": [pubkey]},
            )
            resp.raise_for_status()
            lamports = int(((resp.json() or {}).get("result") or {}).get("value") or 0)
        except Exception as exc:  # noqa: BLE001
            logger.info("solana_agent_wallet: balance read failed (%s)", exc)
            return None

        spendable = max(0, lamports - RESERVED_LAMPORTS) / 1e9
        try:
            price = await coingecko_client.get_simple_price(["solana"], vs_currencies=["usd"])
            sol_usd = price.prices.get("solana", {}).get("usd") if price.available else None
        except Exception as exc:  # noqa: BLE001
            logger.info("solana_agent_wallet: SOL/USD price failed (%s)", exc)
            return None
        if not sol_usd:
            return None
        return spendable * float(sol_usd)
    finally:
        if owns:
            await client.aclose()


# --- latency budget (22/08) -------------------------------------------------
# Measured on the real path: preparing a buy cost 245ms, of which 150ms was a
# single CoinGecko call for the SOL price -- 61% of the budget for a number
# that moves by fractions of a percent per minute.
#
# The price now comes from JUPITER, not an external aggregator: a SOL->USDC
# quote IS the dollar price by construction, it comes from the same venue that
# executes the trade, and it measured 25ms against CoinGecko's 150ms. The
# shadow pockets already treat this price as a slow-moving calibration
# (`pumpswap_ws.SOL_USD_CALIBRATION_REFRESH_SECONDS = 240`), so caching it here
# follows the pattern already established rather than inventing one.
#
# Decimals are cached for the process lifetime -- a mint's decimals are
# immutable, so there is nothing to expire.
# Neither leg waits for a Solana slot (22/08). A slot is ~400ms, so the
# operator's 500ms target is only reachable by returning as soon as the chain
# accepts the transaction.
#
# The reason waiting was worth dropping differs per leg, and the difference
# matters more than the shared constant:
#   * BUY  -- the wait sat between the decision and the position being
#     tracked, on a curve that measured -10.5% real against +35% simulated.
#   * SELL -- the wait changes NOTHING about the price obtained; the swap is
#     already sent and priced. What it blocked was the exit LOOP: 800ms per
#     position, so ten positions meant eight seconds during which no other
#     stop could fire. That, not the fill, is what it cost.
#
# This is only safe because `solana_late_bonding_shadow.reconcile_with_chain`
# repairs both possible disagreements afterwards -- a buy that never landed is
# cancelled, a sell that never landed REOPENS the position so the exit rule
# retries. Without that reconciliation running, these must go back to
# COMMITMENT_CONFIRMED.
# How many fresh-quote attempts a sell gets before giving up for this pass.
_SELL_RETRY_ATTEMPTS = 3

BUY_COMMITMENT = jupiter_swap_signer.COMMITMENT_SENT
SELL_COMMITMENT = jupiter_swap_signer.COMMITMENT_SENT

_SOL_USD_TTL_SECONDS = 60.0
_USDC_MINT = "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v"
_USDC_DECIMALS = 6
_sol_usd_cache: tuple[float, float] | None = None
_decimals_cache: dict[str, int] = {}


async def sol_usd_cached(*, client: httpx.AsyncClient | None = None) -> float | None:
    """SOL price in dollars, at most `_SOL_USD_TTL_SECONDS` old.

    Jupiter first, CoinGecko only as a fallback. Returns None when neither
    knows -- the pilot treats that as a refusal, never as a guess.
    """
    import time

    global _sol_usd_cache
    now = time.monotonic()
    if _sol_usd_cache and now - _sol_usd_cache[0] < _SOL_USD_TTL_SECONDS:
        return _sol_usd_cache[1]

    value: float | None = None
    try:
        # One SOL, priced in USDC. No aggregator, no extra dependency, and the
        # rate is the one our own trades will actually get.
        quote = await jupiter.fetch_quote(
            jupiter.SOL_MINT, _USDC_MINT, 1_000_000_000, slippage_bps=100, client=client,
        )
        out = int(quote.get("outAmount") or 0)
        if out:
            value = out / (10 ** _USDC_DECIMALS)
    except Exception as exc:  # noqa: BLE001 -- fall through to the aggregator
        logger.info("solana_agent_wallet: SOL/USD via Jupiter failed (%s)", exc)

    if value is None:
        try:
            price = await coingecko_client.get_simple_price(["solana"], vs_currencies=["usd"])
            raw = price.prices.get("solana", {}).get("usd") if price.available else None
            value = float(raw) if raw else None
        except Exception as exc:  # noqa: BLE001
            logger.info("solana_agent_wallet: SOL/USD fallback failed (%s)", exc)

    if value:
        _sol_usd_cache = (now, float(value))
        return float(value)
    # A failed refresh keeps the last known price rather than blocking: a
    # slightly stale rate is a better basis for sizing than no trade at all,
    # and the dollar cap is enforced against the real balance regardless.
    return _sol_usd_cache[1] if _sol_usd_cache else None


async def _swap(*, mint: str, amount_in_usd: float, slippage_bps: int) -> dict:
    """Quote then execute. Raises on any problem -- the pilot turns that into a
    logged refusal rather than an exception reaching the pocket."""
    async with httpx.AsyncClient(timeout=30.0) as client:
        sol_usd = await sol_usd_cached(client=client)
        if not sol_usd:
            raise RuntimeError("SOL/USD unavailable, refusing to size a real swap blind")
        sol_amount = amount_in_usd / float(sol_usd)

        quote = await jupiter.quote_sol_for_token(mint, sol_amount, client=client)
        # `confirmed`, not `finalized`: this path records a price the quote
        # already gave and never reads on-chain state afterwards, so the race
        # that justified `finalized` cannot occur here. Measured cost of the
        # stricter level: 12-13 seconds on a collapsing bonding curve.
        result = await jupiter_swap_signer.execute_swap(
            quote, key_path(), client=client,
            commitment=BUY_COMMITMENT,
        )
        status = (result or {}).get("status")
        if status != "ok":
            # "unknown" means it may still land: surfaced as a failure so the
            # pocket does not record a position, but named so the operator can
            # tell it apart from a clean refusal in the journal.
            raise RuntimeError(f"swap status={status!r} (tx={(result or {}).get('tx')})")

        out_amount = float((result or {}).get("out_amount") or 0)
        # Jupiter returns RAW units. Dividing by them directly yields a price
        # per raw unit, which for a 6-decimal token is a million times too low
        # -- found live on the first real automated buy, recorded at 1.6e-11
        # against a real 1.6e-5. Every downstream comparison against a market
        # price in dollars-per-token would then be nonsense, so the exit rule
        # was reading a position that did not exist.
        decimals = await token_decimals(mint, client=client)
        if decimals is None:
            raise RuntimeError(f"decimals unreadable for {mint}, refusing to record a blind price")
        tokens = out_amount / (10 ** decimals)
        entry_price = (amount_in_usd / tokens) if tokens else None
        return {"tx_hash": (result or {}).get("tx") or "", "entry_price": entry_price}


async def token_decimals(mint: str, *, client: httpx.AsyncClient | None = None) -> int | None:
    """Decimals of `mint`, or None if unreadable -- never a guessed default.

    A wrong decimals value silently rescales every price by a power of ten, so
    an unknown one must refuse the trade rather than assume the common 6 or 9.
    """
    cached = _decimals_cache.get(mint)
    if cached is not None:
        return cached
    owns = client is None
    client = client or httpx.AsyncClient(timeout=20.0)
    try:
        resp = await client.post(
            require_solana_rpc_http(),
            json={
                "jsonrpc": "2.0", "id": 1, "method": "getAccountInfo",
                "params": [mint, {"encoding": "jsonParsed"}],
            },
        )
        resp.raise_for_status()
        value = ((resp.json() or {}).get("result") or {}).get("value") or {}
        parsed = ((value.get("data") or {}).get("parsed") or {}).get("info") or {}
        decimals = parsed.get("decimals")
        if decimals is None:
            return None
        _decimals_cache[mint] = int(decimals)
        return int(decimals)
    except Exception as exc:  # noqa: BLE001
        logger.info("solana_agent_wallet: decimals unreadable for %s (%s)", mint, exc)
        return None
    finally:
        if owns:
            await client.aclose()


async def execute_real_buy(mint: str, pool_address: str, *, chain: str = "solana",
                           quoted_price: float | None = None) -> dict | None:
    """The pocket's `execute_fn`. Returns the fill, or None if anything refused.

    Signature matches what `consider_candidate` expects, so wiring it is a
    one-line change in the host process -- and unwiring it likewise.
    """
    if chain != "solana":
        return None
    result = await solana_trade_pilot.attempt_buy(
        mint=mint,
        amount_in_usd=solana_trade_pilot.MAX_TRADE_USD,
        balance_fn=get_balance_usd,
        swap_fn=_swap,
        quoted_price=quoted_price,
    )
    if not result.ok:
        return None
    # `tx`, not `tx_hash`: `consider_candidate` reads `filled.get("tx")`. The
    # mismatch cost nothing visible -- a real buy still recorded a position --
    # but silently dropped the one field that lets a row be audited on-chain.
    return {"entry_price": result.entry_price or quoted_price, "tx": result.tx_hash}


async def token_balance(mint: str, *, client: httpx.AsyncClient | None = None) -> int | None:
    """Raw units of `mint` actually held, or None if unreadable.

    Read live rather than tracked: the pocket's `remaining_qty` is a FRACTION
    of a simulated position, and any drift between it and the wallet's real
    holding would compound silently across partial exits. The chain is the only
    authority on what can be sold.
    """
    owns = client is None
    client = client or httpx.AsyncClient(timeout=20.0)
    try:
        from solders.keypair import Keypair
        import json

        with open(key_path(), encoding="utf-8") as fh:
            pubkey = str(Keypair.from_bytes(bytes(json.load(fh))).pubkey())

        resp = await client.post(
            require_solana_rpc_http(),
            json={
                "jsonrpc": "2.0", "id": 1, "method": "getTokenAccountsByOwner",
                "params": [pubkey, {"mint": mint}, {"encoding": "jsonParsed"}],
            },
        )
        resp.raise_for_status()
        accounts = ((resp.json() or {}).get("result") or {}).get("value") or []
        total = 0
        for account in accounts:
            info = account["account"]["data"]["parsed"]["info"]
            total += int((info.get("tokenAmount") or {}).get("amount") or 0)
        return total
    except Exception as exc:  # noqa: BLE001 -- unknown is never zero
        if "429" in str(exc):
            from aria_core.services import pumpswap_ws

            pumpswap_ws.note_rpc_http_exhausted()
        logger.info("solana_agent_wallet: token balance unreadable for %s (%s)", mint, exc)
        return None
    finally:
        if owns:
            await client.aclose()


async def _swap_out(*, mint: str, amount_units: int, slippage_bps: int) -> dict:
    """Sells `amount_units` of `mint` back to SOL. Mirror of `_swap`."""
    async with httpx.AsyncClient(timeout=30.0) as client:
        quote = await jupiter.fetch_quote(
            mint, jupiter.SOL_MINT, amount_units,
            slippage_bps=slippage_bps, client=client,
        )
        result = await jupiter_swap_signer.execute_swap(
            quote, key_path(), client=client,
            commitment=SELL_COMMITMENT,
        )
        status = (result or {}).get("status")
        if status != "ok":
            raise RuntimeError(f"sell status={status!r} (tx={(result or {}).get('tx')})")

        lamports_out = float((result or {}).get("out_amount") or 0)
        sol_usd = await sol_usd_cached(client=client)
        proceeds_usd = (lamports_out / 1e9) * float(sol_usd) if sol_usd else None
        # Same raw-units trap as the buy side: `amount_units` is raw, and an
        # exit price per raw unit would not be comparable to the entry price.
        decimals = await token_decimals(mint, client=client)
        tokens_sold = (amount_units / (10 ** decimals)) if decimals is not None else None
        exit_price = (
            proceeds_usd / tokens_sold if (proceeds_usd and tokens_sold) else None
        )
        return {
            "tx": (result or {}).get("tx") or "",
            "exit_price": exit_price,
            "proceeds_usd": proceeds_usd,
            "units_sold": amount_units,
        }


async def execute_real_sell(mint: str, fraction: float, *, chain: str = "solana") -> dict | None:
    """The pocket's `sell_fn`: sells `fraction` of what is really held.

    Returns None on any refusal, which the pocket must treat as "the position
    is still open" -- recording a closure that did not happen would leave real
    tokens stranded while the table claims they were sold, the exact failure
    this seam exists to prevent.

    A fraction at or above 1 sells the entire real balance, so a full exit can
    never leave dust behind through a rounding error.

    **Deliberately NOT behind the kill-switch, unlike every buy.** `outgoing_pause`
    exists to stop value LEAVING; a sell converts a collapsing memecoin back into
    SOL in the same wallet, reducing exposure rather than spending it. Gating it
    would mean hitting the emergency stop traps the capital in exactly the
    positions the operator wanted out of -- same reasoning that puts
    `solana_cold_sweep` outside the raise-exposure guardrails.
    """
    if chain != "solana":
        return None
    if fraction <= 0:
        return None

    held = await token_balance(mint)
    if held is None:
        logger.warning("solana_agent_wallet: refusing to sell %s, balance unreadable", mint)
        return None
    if held <= 0:
        return None

    units = held if fraction >= 1.0 else int(held * fraction)
    if units <= 0:
        return None

    # A sell that fails on slippage (Jupiter 0x1771 / 6001) means the price
    # moved more than 10% between the quote and execution -- routine on a
    # collapsing curve. Raising the ceiling is not an option: 10% is an
    # absolute project rule. The answer is a FRESH quote immediately, not the
    # same stale one, and not a retry one full loop later while the token
    # keeps falling.
    #
    # Bounded at three attempts: past that the market is moving faster than we
    # can quote it, and the exit rule will try again on its next pass anyway.
    last_error: Exception | None = None
    for attempt in range(_SELL_RETRY_ATTEMPTS):
        if attempt:
            # Re-read the balance too: a partial fill would make the old
            # amount wrong, and selling more than is held fails differently.
            held = await token_balance(mint)
            if not held:
                return None
            units = held if fraction >= 1.0 else int(held * fraction)
            if units <= 0:
                return None
        try:
            return await _swap_out(
                mint=mint, amount_units=units,
                slippage_bps=solana_trade_pilot.MAX_SLIPPAGE_BPS,
            )
        except Exception as exc:  # noqa: BLE001 -- a failed sell is not a closure
            last_error = exc
    logger.warning(
        "solana_agent_wallet: real sell failed for %s after %d attempts (%s)",
        mint, _SELL_RETRY_ATTEMPTS, last_error,
    )
    return None
