"""Adapter wiring the late-bonding pocket to a REAL Solana wallet (22/08).

Three pieces already existed and did their job in isolation:

  * `services/jupiter.py`          -- executable quotes
  * `onchain/jupiter_swap_signer`  -- simulate, sign, send, await finalized
  * `solana_trade_pilot`           -- gate, kill-switch, caps, journalling

Nothing connected them, so the pocket's `execute_fn` seam stayed empty. This
module is that connection and nothing more: it holds no policy of its own, adds
no cap, and cannot bypass anything. Every real buy still goes THROUGH
`solana_trade_pilot.attempt_buy`, which is where the refusals live.

Balance is read fresh from mainnet on every attempt and converted with a live
SOL/USD price. A price that cannot be read returns None, which the pilot treats
as fail-closed -- an unpriced balance blocks the trade rather than being
assumed. That is deliberate: the alternative is trading against a stale
exchange rate, which silently breaks the dollar cap the operator set.

Ships unusable: the pilot's gate is OFF and no key file exists until the
operator creates one.
"""

from __future__ import annotations

import logging
import os

import httpx

from aria_core import solana_trade_pilot
from aria_core.onchain import jupiter_swap_signer
from aria_core.services import jupiter
from aria_core.services.coingecko import coingecko_client
from aria_core.services.pumpswap_ws import require_solana_rpc_http

logger = logging.getLogger(__name__)

# Where the delegate key lives. No default path baked into the signer itself
# (fail-closed by design there), so the choice is made here, once, and stays
# greppable. chmod 600, generated by solana-keygen, never read into a log.
KEY_PATH_ENV = "ARIA_SOLANA_DELEGATE_KEY_PATH"
DEFAULT_KEY_PATH = "/opt/aria-data/agent-wallet-solana-mainnet/delegate.json"

# Lamports kept untouched for fees and rent-exemption. A Solana token account
# costs ~0.00204 SOL to open and every transaction pays a fee; a wallet drained
# to zero cannot even sell what it holds. Roughly 0.01 SOL of headroom.
RESERVED_LAMPORTS = 10_000_000


def key_path() -> str:
    return (os.environ.get(KEY_PATH_ENV, "") or "").strip() or DEFAULT_KEY_PATH


def delegate_key_available() -> bool:
    """True only if the key file really exists AND is not group/world readable.
    The signer refuses a loose key anyway; checking here lets the caller know
    BEFORE a trade is attempted rather than after."""
    path = key_path()
    try:
        st = os.stat(path)
    except OSError:
        return False
    return not (st.st_mode & 0o077)


async def get_balance_usd(*, client: httpx.AsyncClient | None = None) -> float | None:
    """Spendable balance in dollars, or None if anything is unknown.

    None is a REFUSAL upstream, never a zero: the pilot blocks when the balance
    cannot be read. Reserved lamports are subtracted here so the cap applies to
    what is genuinely spendable, not to a total that includes money the wallet
    must keep to pay its own fees.
    """
    owns = client is None
    client = client or httpx.AsyncClient(timeout=20.0)
    try:
        try:
            from solders.keypair import Keypair
            import json

            with open(key_path(), encoding="utf-8") as fh:
                pubkey = str(Keypair.from_bytes(bytes(json.load(fh))).pubkey())
        except Exception as exc:  # noqa: BLE001 -- no key, no balance, no trade
            logger.info("solana_agent_wallet: cannot resolve wallet pubkey (%s)", exc)
            return None

        try:
            resp = await client.post(
                require_solana_rpc_http(),
                json={"jsonrpc": "2.0", "id": 1, "method": "getBalance", "params": [pubkey]},
            )
            resp.raise_for_status()
            lamports = int(((resp.json() or {}).get("result") or {}).get("value") or 0)
        except Exception as exc:  # noqa: BLE001
            logger.info("solana_agent_wallet: balance read failed (%s)", exc)
            return None

        spendable = max(0, lamports - RESERVED_LAMPORTS) / 1e9
        try:
            price = await coingecko_client.get_simple_price(["solana"], vs_currencies=["usd"])
            sol_usd = price.prices.get("solana", {}).get("usd") if price.available else None
        except Exception as exc:  # noqa: BLE001
            logger.info("solana_agent_wallet: SOL/USD price failed (%s)", exc)
            return None
        if not sol_usd:
            return None
        return spendable * float(sol_usd)
    finally:
        if owns:
            await client.aclose()


async def _swap(*, mint: str, amount_in_usd: float, slippage_bps: int) -> dict:
    """Quote then execute. Raises on any problem -- the pilot turns that into a
    logged refusal rather than an exception reaching the pocket."""
    async with httpx.AsyncClient(timeout=30.0) as client:
        price = await coingecko_client.get_simple_price(["solana"], vs_currencies=["usd"])
        sol_usd = price.prices.get("solana", {}).get("usd") if price.available else None
        if not sol_usd:
            raise RuntimeError("SOL/USD unavailable, refusing to size a real swap blind")
        sol_amount = amount_in_usd / float(sol_usd)

        quote = await jupiter.quote_sol_for_token(mint, sol_amount, client=client)
        result = await jupiter_swap_signer.execute_swap(
            quote, key_path(), client=client,
        )
        status = (result or {}).get("status")
        if status != "ok":
            # "unknown" means it may still land: surfaced as a failure so the
            # pocket does not record a position, but named so the operator can
            # tell it apart from a clean refusal in the journal.
            raise RuntimeError(f"swap status={status!r} (tx={(result or {}).get('tx')})")

        out_amount = float((result or {}).get("out_amount") or 0)
        entry_price = (amount_in_usd / out_amount) if out_amount else None
        return {"tx_hash": (result or {}).get("tx") or "", "entry_price": entry_price}


async def execute_real_buy(mint: str, pool_address: str, *, chain: str = "solana",
                           quoted_price: float | None = None) -> dict | None:
    """The pocket's `execute_fn`. Returns the fill, or None if anything refused.

    Signature matches what `consider_candidate` expects, so wiring it is a
    one-line change in the host process -- and unwiring it likewise.
    """
    if chain != "solana":
        return None
    result = await solana_trade_pilot.attempt_buy(
        mint=mint,
        amount_in_usd=solana_trade_pilot.MAX_TRADE_USD,
        balance_fn=get_balance_usd,
        swap_fn=_swap,
        quoted_price=quoted_price,
    )
    if not result.ok:
        return None
    return {"entry_price": result.entry_price or quoted_price, "tx_hash": result.tx_hash}
