"""Auto-reply on watched external showcase PR threads (e.g. Virtual-Protocol/acp-cli-demos#37)."""
from __future__ import annotations

import json
import logging
import re
from datetime import datetime, timezone
from functools import lru_cache
from pathlib import Path
from typing import Any

import yaml

from aria_core.github_client import GitHubClient
from aria_core.memory import append_memory
from aria_core.paths import memory_dir
from aria_core.runtime import settings
from aria_core.skills.github_skill import github_configured

logger = logging.getLogger(__name__)

_WATCH_CMD_RE = re.compile(
    r"(?i)(?:showcase\s+pr\s+watch|watch\s+showcase\s+pr|surveiller\s+pr\s+showcase|pr\s+37\s+watch)"
)

_REGISTRY_PATH = (
    Path(__file__).resolve().parent.parent / "knowledge" / "showcase_pr_watch.yaml"
)
_STATE_PATH = memory_dir() / "showcase_pr_watch_state.json"

# Signature de transparence : toute reponse postee par ARIA l'annonce comme telle
# (agent autonome). Voix humaine, aucun em-dash, aucun emoji (norme surfaces publiques).
_SIGNATURE = (
    "\n\n---\n"
    "Response generated by ARIA, an autonomous AI powered by GoldenFarFR."
)


def _sign(body: str) -> str:
    """Ajoute la signature de transparence a une reponse destinee a etre postee."""
    return body.rstrip() + _SIGNATURE


# ARIA ne poste seule QUE le cas net et sans risque : feu vert/merge (plan de reouverture).
# Aucune affirmation de fait non verifiable (pas de "API 500" assene comme fait courant).
# TOUT le reste (question, sujet technique, negatif, ambigu) -> passage de relai a l'humain.
_THANKS_REOPEN_TEMPLATE = """Thanks for the review.

We will reopen PR #{pr_number} once we have:
- `node scripts/validate-showcase.mjs` passing, and
- a funded escrow job receipt with a public job id (pending a successful provider submit on our side).

Package remains on `GoldenFarFR/acp-cli-demos@showcase/aria-vanguard-zhc` until then.
"""

# Passage de relai : quand ca devient technique (ou tout cas ou ARIA ne peut pas repondre
# en confiance), elle poste ce court message public en taguant l'operateur (transparent :
# elle est un agent, un humain prend la suite) ET ping l'operateur en prive. Elle n'invente
# rien, elle ne tranche rien. {operator} = handle GitHub de l'operateur.
_HANDOVER_TEMPLATE = """Thanks for your comment.

This point is for a human, so I am handing it over to my operator @{operator}, who will follow up here shortly.
"""

# Brouillon SUGGERE a l'operateur lors d'une escalade (jamais poste automatiquement) :
# il le copie/edite s'il veut. Pas d'affirmation de panne non verifiee.
_OPERATOR_DRAFT_TEMPLATE = """Thanks for the comment.

Clarifying our situation (not a showcase format issue):
- Agent: Aria Vanguard ZHC (HYBRID provider, Base chain 8453)
- Live offering: {offering} on the ACP marketplace

We closed PR #{pr_number} ourselves until the receipt gate is green, not because the package is invalid.

Questions for the team:
1. Is this a known incident on your side?
2. Any ETA or workaround for provider submit?
3. Should we reopen after a successful funded job, or track this in a separate issue?
"""


def wants_showcase_pr_watch(message: str) -> bool:
    return bool(_WATCH_CMD_RE.search((message or "").strip()))


@lru_cache(maxsize=1)
def _acp_agent_ssot() -> dict[str, str]:
    path = Path(__file__).resolve().parent.parent / "knowledge" / "acp_config.yaml"
    if not path.is_file():
        return {}
    data = yaml.safe_load(path.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        return {}
    return {
        "agent_id": str(data.get("agent_id") or "").strip(),
        "agent_name": str(data.get("agent_name") or "").strip(),
    }


@lru_cache(maxsize=1)
def load_watch_targets() -> list[dict[str, Any]]:
    if not _REGISTRY_PATH.is_file():
        return []
    data = yaml.safe_load(_REGISTRY_PATH.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        return []
    ssot = _acp_agent_ssot()
    targets = data.get("targets") or []
    out: list[dict[str, Any]] = []
    for t in targets:
        if not isinstance(t, dict) or not t.get("enabled"):
            continue
        merged = dict(t)
        if ssot.get("agent_id"):
            merged["agent_id"] = ssot["agent_id"]
        out.append(merged)
    return out


def _load_state() -> dict[str, Any]:
    if not _STATE_PATH.is_file():
        return {"handled": {}, "replies": []}
    try:
        return json.loads(_STATE_PATH.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return {"handled": {}, "replies": []}


def _save_state(state: dict[str, Any]) -> None:
    _STATE_PATH.parent.mkdir(parents=True, exist_ok=True)
    state["replies"] = list(state.get("replies") or [])[-200:]
    _STATE_PATH.write_text(json.dumps(state, indent=2, ensure_ascii=False), encoding="utf-8")


def _our_logins(target: dict[str, Any]) -> set[str]:
    raw = target.get("our_logins") or ["GoldenFarFR"]
    return {str(x).strip().lower() for x in raw if str(x).strip()}


def _test_reviewer_marker(target: dict[str, Any]) -> str:
    return str(target.get("test_reviewer_marker") or "").strip()


def _is_external_comment(row: dict[str, Any], ours: set[str], target: dict[str, Any]) -> bool:
    author_l = (row.get("author") or "").lower()
    body = (row.get("body") or "").strip()
    marker = _test_reviewer_marker(target)
    if marker and marker in body:
        return True
    return bool(author_l and author_l not in ours)


def _already_answered_by_us(
    comments: list[dict[str, Any]],
    external_row: dict[str, Any],
    ours: set[str],
) -> bool:
    """Skip auto-reply if operator already posted after this external comment."""
    ext_at = (external_row.get("created_at") or "").strip()
    if not ext_at:
        return False
    for row in comments:
        author_l = (row.get("author") or "").lower()
        if author_l not in ours:
            continue
        ours_at = (row.get("created_at") or "").strip()
        if ours_at and ours_at > ext_at:
            return True
    return False


def _comment_key(kind: str, comment_id: int | str) -> str:
    return f"{kind}:{comment_id}"


# Feu vert net : ARIA peut repondre seule (plan de reouverture).
_MERGE_RE = re.compile(r"\b(?:merge|approved|lgtm|looks good|ship it|ready to merge)\b", re.IGNORECASE)
# Signaux « ARIA ne tranche pas » -> passage de relai a l'humain (biais volontaire vers l'escalade :
# sur-escalader est sans risque (un ping), sous-escalader poste une betise en public).
_NEGATION_RE = re.compile(
    r"\b(?:not|don'?t|do not|never|cannot|can'?t|won'?t|isn'?t|aren'?t|"
    r"reject|declin\w*|refus\w*|invalid|premature|spam|closing|close this)\b",
    re.IGNORECASE,
)
_QUESTION_RE = re.compile(
    r"\?|"
    r"\bwhy\b|what'?s|what is|\bhow (?:do|does|can|to)\b|when will|which one|"
    r"(?:can|could|would|will|do)\s+you\b|"
    r"don'?t understand|do not understand|not clear|unclear|confused|explain|clarify",
    re.IGNORECASE,
)
# Sujets techniques/incident : jamais une reponse toute faite -> l'humain regarde.
_TECHNICAL_RE = re.compile(
    r"\b(?:500|privy|alchemy|signer|add-signer|adapter|incident|outage|degraded|"
    r"maintenance|known issue|error|stack trace|traceback|urgent|asap)\b",
    re.IGNORECASE,
)


def _reply_ctx(target: dict[str, Any]) -> dict[str, Any]:
    return {
        "agent_id": target.get("agent_id") or "019f0522-b57b-7e8e-a70a-aab2070e070e",
        "offering": target.get("offering") or "analyse_lite_x1",
        "pr_number": int(target.get("pr_number") or 0),
    }


def _operator_handle(target: dict[str, Any]) -> str:
    """Handle GitHub de l'operateur a taguer dans le message de passage de relai."""
    logins = [str(x).lstrip("@").strip() for x in (target.get("our_logins") or []) if str(x).strip()]
    return logins[0] if logins else "GoldenFarFR"


def _handover_message(target: dict[str, Any]) -> str:
    return _HANDOVER_TEMPLATE.format(operator=_operator_handle(target))


def handover_reason(their_body: str) -> str:
    """Etiquette courte du motif d'escalade, pour le ping operateur (contexte humain)."""
    low = (their_body or "").strip().lower()
    if _QUESTION_RE.search(low):
        return "question a laquelle ARIA ne peut pas repondre avec certitude"
    if _NEGATION_RE.search(low):
        return "point negatif/bloquant"
    if _TECHNICAL_RE.search(low):
        return "sujet technique (incident/signer/erreur)"
    return "cas ambigu, hors des reponses sures"


def decide_reply(their_body: str, *, target: dict[str, Any]) -> tuple[str, str]:
    """Decide quoi faire d'un commentaire externe.

    Retourne (action, payload) :
    - ("reply", corps)  : cas net et sans risque (feu vert/merge), ARIA repond seule.
    - ("handover", "")  : tout le reste -> ARIA poste un court relai public + ping operateur.

    Regle : ARIA ne repond seule QUE sur un feu vert clair SANS negation, SANS question,
    SANS sujet technique. Sinon elle passe la main (elle n'invente ni ne tranche rien).
    """
    low = (their_body or "").strip().lower()
    safe_green_light = (
        bool(_MERGE_RE.search(low))
        and not _NEGATION_RE.search(low)
        and not _QUESTION_RE.search(low)
        and not _TECHNICAL_RE.search(low)
    )
    if safe_green_light:
        return "reply", _THANKS_REOPEN_TEMPLATE.format(**_reply_ctx(target))
    return "handover", ""


def _normalize_comments(
    issue_comments: list[dict[str, Any]],
    reviews: list[dict[str, Any]],
) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    for row in issue_comments:
        author = ((row.get("user") or {}).get("login") or "").strip()
        cid = row.get("id")
        body = (row.get("body") or "").strip()
        if not cid or not body:
            continue
        rows.append(
            {
                "key": _comment_key("issue", cid),
                "id": cid,
                "kind": "issue",
                "author": author,
                "body": body,
                "created_at": row.get("created_at") or "",
                "url": row.get("html_url") or "",
            }
        )
    for row in reviews:
        author = ((row.get("user") or {}).get("login") or "").strip()
        rid = row.get("id")
        body = (row.get("body") or "").strip()
        if not rid or not body:
            continue
        rows.append(
            {
                "key": _comment_key("review", rid),
                "id": rid,
                "kind": "review",
                "author": author,
                "body": body,
                "created_at": row.get("submitted_at") or row.get("created_at") or "",
                "url": row.get("html_url") or "",
            }
        )
    rows.sort(key=lambda r: r.get("created_at") or "")
    return rows


async def run_showcase_pr_watch(*, post_replies: bool = True) -> dict[str, Any]:
    result: dict[str, Any] = {
        "ok": False,
        "targets": 0,
        "scanned": 0,
        "new_external": 0,
        "replied": [],
        "handed_over": [],
        "errors": [],
    }

    if not github_configured():
        result["errors"].append("GITHUB_TOKEN missing")
        return result

    targets = load_watch_targets()
    result["targets"] = len(targets)
    if not targets:
        result["errors"].append("no watch targets enabled")
        return result

    client = GitHubClient(settings.github_token.strip())
    state = _load_state()
    handled: dict[str, str] = dict(state.get("handled") or {})
    replies_log: list[dict[str, Any]] = list(state.get("replies") or [])

    for target in targets:
        owner = str(target.get("owner") or "").strip()
        repo = str(target.get("repo") or "").strip()
        pr_number = int(target.get("pr_number") or 0)
        if not owner or not repo or pr_number < 1:
            continue

        ours = _our_logins(target)
        try:
            issue_comments = await client.list_issue_comments(owner, repo, pr_number)
            reviews = await client.list_pull_reviews(owner, repo, pr_number)
        except Exception as exc:
            logger.warning("showcase_pr_watch fetch failed %s/%s#%s: %s", owner, repo, pr_number, exc)
            result["errors"].append(f"{owner}/{repo}#{pr_number}: {exc}")
            continue

        comments = _normalize_comments(issue_comments, reviews)
        result["scanned"] += len(comments)

        for row in comments:
            key = row.get("key") or ""
            if not key or not _is_external_comment(row, ours, target):
                continue
            if key in handled:
                continue
            if _already_answered_by_us(comments, row, ours):
                handled[key] = "human-replied"
                continue

            result["new_external"] += 1
            body_in = row.get("body") or ""
            action, payload = decide_reply(body_in, target=target)
            is_handover = action == "handover"
            # Corps public : reponse sure signee, ou court message de relai (tag operateur) signe.
            post_body = _sign(_handover_message(target) if is_handover else payload)
            reply_meta: dict[str, Any] = {
                "target": target.get("id") or f"{owner}/{repo}#{pr_number}",
                "trigger_key": key,
                "trigger_author": row.get("author"),
                "trigger_url": row.get("url"),
                "handover": is_handover,
                "at": datetime.now(timezone.utc).isoformat(),
            }
            if is_handover:
                reply_meta["reason"] = handover_reason(body_in)
                reply_meta["comment_excerpt"] = body_in.strip()[:400]
                reply_meta["suggested_draft"] = _OPERATOR_DRAFT_TEMPLATE.format(**_reply_ctx(target))
            bucket = "handed_over" if is_handover else "replied"
            kind = "handover-relay" if is_handover else "auto-reply"

            if post_replies:
                try:
                    posted = await client.create_issue_comment(owner, repo, pr_number, post_body)
                    reply_meta["reply_id"] = posted.get("id")
                    reply_meta["reply_url"] = posted.get("html_url")
                    handled[key] = str(posted.get("id") or "posted")
                    replies_log.append(reply_meta)
                    result[bucket].append(reply_meta)
                    append_memory(
                        "github",
                        f"[showcase_pr] {kind} to @{row.get('author')} on {owner}/{repo}#{pr_number}",
                    )
                except Exception as exc:
                    logger.warning("showcase_pr_watch %s failed: %s", kind, exc)
                    result["errors"].append(f"{kind} {key}: {exc}")
            else:
                handled[key] = "dry-run"
                reply_meta["dry_run"] = True
                result[bucket].append(reply_meta)

    state["handled"] = handled
    state["replies"] = replies_log
    state["last_scan_at"] = datetime.now(timezone.utc).isoformat()
    _save_state(state)

    result["ok"] = not result["errors"] or bool(result["replied"]) or bool(result["handed_over"])
    return result


async def execute_showcase_pr_watch(message: str, lang: str = "fr") -> tuple[str, dict]:
    dry = "dry" in (message or "").lower() or "test" in (message or "").lower()
    scan = await run_showcase_pr_watch(post_replies=not dry)
    replied = scan.get("replied") or []
    handed = scan.get("handed_over") or []
    lines = [
        "SHOWCASE PR WATCH",
        f"Targets: {scan.get('targets', 0)} · scanned: {scan.get('scanned', 0)} · "
        f"new external: {scan.get('new_external', 0)} · replied: {len(replied)} · "
        f"handover: {len(handed)}",
    ]
    if scan.get("errors"):
        lines.append("Errors:")
        for err in scan["errors"][:4]:
            lines.append(f"  - {err}")
    for row in replied[:3]:
        lines.append(f"  reply @{row.get('trigger_author')} · {row.get('reply_url') or 'dry-run'}")
    for row in handed[:3]:
        lines.append(f"  handover @{row.get('trigger_author')} ({row.get('reason')})")
    return "\n".join(lines), {"github": "showcase_pr_watch", "scan": scan}